variables:
  AWS_REGION: ap-southeast-2

default:
  image:
    name: 307973494033.dkr.ecr.ap-southeast-2.amazonaws.com/dev/serverless/maven-build-centos:v25032
    pull_policy: [if-not-present, always]
  before_script:
    - |
      # Job details
      echo "CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME , CI_COMMIT_TAG = $CI_COMMIT_TAG , CI_COMMIT_TITLE = $CI_COMMIT_TITLE"
      echo "CI_PARENT_PIPELINE_ID = $CI_PARENT_PIPELINE_ID"

stages:
  - "provision"
  - "deploy"

provision:
  stage: "provision"
  environment:
    name: $CI_ENVIRONMENT_NAME
  tags:
    - $RUNNER_TAG
  script:
    - |
      # Provision AWS resources
      python3 -m cicd --cmd provision --version-id $CI_PARENT_PIPELINE_ID --unit provision-bua-queues
      python3 -m cicd --cmd provision --version-id $CI_PARENT_PIPELINE_ID --unit provision-bua-buckets
      python3 -m cicd --cmd provision --version-id $CI_PARENT_PIPELINE_ID --unit provision-bua-secrets
      python3 -m cicd --cmd provision --version-id $CI_PARENT_PIPELINE_ID --unit provision-bua-dynamodb
    - |
      # Upload stepfunction definitions
      python3 -m cicd --cmd upload --bucket ${CI_ENVIRONMENT_NAME}-s3-bua --versioned --version-id $CI_PARENT_PIPELINE_ID --upload-type states --file reset-basicreads-machine.json
      python3 -m cicd --cmd upload --bucket ${CI_ENVIRONMENT_NAME}-s3-bua --versioned --version-id $CI_PARENT_PIPELINE_ID --upload-type states --file basicreads-machine.json
      python3 -m cicd --cmd upload --bucket ${CI_ENVIRONMENT_NAME}-s3-bua --versioned --version-id $CI_PARENT_PIPELINE_ID --upload-type states --file invoiceruns-machine.json
    - |
      # Package python for aws lambda layers
      rm -fr ./target/packages
      pip3 install --target ./target/packages --ignore-installed -r runtime-requirements.txt
      python3 -m cicd --cmd package --version-id $CI_PARENT_PIPELINE_ID --unit bua --package bua
    - |
      # Release new python aws lambda layer
      python3 -m cicd --cmd release-python --version-id $CI_PARENT_PIPELINE_ID --bucket ${CI_ENVIRONMENT_NAME}-s3-bua --unit bua
  variables:
    CF_ROLE: CloudformationProvisionRole

deploy:
  stage: "deploy"
  tags:
    - $RUNNER_TAG
  script:
    - |
      # Deploy new aws lambda layer
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-layer
    - |
      # Deploy new controller aws lambda function version
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-controller
    - |
      # Deploy new retry aws lambda function version
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-next
    - |
      # Deploy new site data aws lambda function version
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-site-data
    - |
      # Deploy new site initiate aws lambda function version
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-site-initiate
    - |
      # Deploy new site segment aws lambda function version
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-lambda-site-segment
    - |
      # Clean up old lambda layers
      python3 -m cicd --cmd clean-layers --version-id $CI_PARENT_PIPELINE_ID --version $CI_PARENT_PIPELINE_ID --layer "layer-bua-python-libs"
    - |
      # Deploy the reset basic reads state machine
      python3 -m cicd --cmd deploy --version-id $CI_PARENT_PIPELINE_ID --unit deploy-bua-state-machines
  variables:
    CF_ROLE: CloudformationDeployRole
    SLEEP_INTERVAL: 5
  needs:
    - "provision"
