AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Deploy bua aws lambda layers only

Parameters:
  ProjectVersion:
    Description: The version of the project being released
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String

Resources:

  LambdaLayer{{ ProjectVersion }}:
    Type: "AWS::Lambda::LayerVersion"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: !Sub "${ResourcePrefix}-s3-bua"
        S3Key: !Join [ "" , [ "lambda/python/bua-layer-" , !Ref ProjectVersion , ".zip" ] ]
      Description: Python libraries for bua lambda functions
      LayerName: !Join [ "" , [ !Ref ResourcePrefix , "-layer-bua-python-libs-" , !Ref ProjectVersion ] ]

  PandasLayer{{ ProjectVersion }}:
    Type: "AWS::Lambda::LayerVersion"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: !Sub "${ResourcePrefix}-s3-bua"
        S3Key: !Join [ "" , [ "lambda/python/bua-pandas-layer-" , !Ref ProjectVersion , ".zip" ] ]
      Description: Pandas libraries for bua lambda functions
      LayerName: !Join [ "" , [ !Ref ResourcePrefix , "-layer-bua-pandas-python-libs-" , !Ref ProjectVersion ] ]
