AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy bottom up accruals state machines

Parameters:
  EnvironmentName:
    Description: The name of the environment to deploy into
    Type: String
    AllowedValues: [ "dev", "tst", "prd" ]
  ClassName:
    Description: The class of the environment to deploy into
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  ResourcePrefixIAM:
    Description: Prefix to assign to resources
    Type: String
  ResourcePrefixPath:
    Description: Prefix to assign to resources
    Type: String
  ProjectVersion:
    Description: The version of the project being released
    Type: String

Resources:

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub "states.${AWS::Region}.amazonaws.com"
            Action: "sts:AssumeRole"
      RoleName: !Join [ "_" , [ !Ref ResourcePrefixIAM , "BUA" , "BUAResetBasicReadsStatesExecRole" ] ]
      Path: !Join [ "" , [ "/" , !Ref ResourcePrefixPath , "/states/" ] ]
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  ResetBasicReadsMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: !Sub "${ResourcePrefix}-bua-reset-basicreads"
      DefinitionS3Location:
        Bucket: !Sub "${ResourcePrefix}-s3-bua"
        Key: !Sub "states/reset-basicreads-machine.json/${ProjectVersion}"
      DefinitionSubstitutions:
        SlowControllerFunction: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}-lambda-bua-controller-slow"
        FastControllerFunction: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}-lambda-bua-controller-fast"
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName
        - Key: resource-type
          Value: stepfunction
        - Key: resource-class
          Value: data
