AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy bottom up accruals state machines

Parameters:
  EnvironmentName:
    Description: The name of the environment to deploy into
    Type: String
    AllowedValues: [ "dev", "tst", "prd" ]
  ClassName:
    Description: The class of the environment to deploy into
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String

Resources:

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub "states.${AWS::Region}.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  ResetBasicReadsMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: !Sub "${ResourcePrefix}-bua-reset-basicreads"
      DefinitionString:
        !Sub
        - |-
          {
            "Comment": "Reset Basic Reads",
            "StartAt": "ResetReads",
            "States": {
              "ResetReads": {
                "Type": "Pass",
                "Result": {
                  "type": "step",
                  "name": "Reset Reads",
                  "next": "210_clear_error_queues",
                  "speed": "slow",
                  "steps": {
                    "210_clear_error_queues": {
                      "action": "empty_site_errors_queues",
                      "on": {
                        "COMPLETE": {
                          "delay": 60,
                          "next": "210_reset_missing_basic_reads"
                        }
                      }
                    },
                    "210_reset_missing_basic_reads": {
                      "action": "bua_initiate",
                      "args": {
                        "run_type": "ResetBasicRead",
                        "identifier_type": "SegmentJurisdictionAvgExclEst"
                      },
                      "on": {
                        "COMPLETE": {
                          "delay": 120,
                          "next": "210_wait_for_reset_missing_basic_reads"
                        }
                      }
                    },
                    "210_wait_for_reset_missing_basic_reads": {
                      "action": "wait_for_empty_site_queues",
                      "on": {
                        "COMPLETE": {}
                        "FAILED": {}
                      }
                    }
                  }
                },
                "Next": "NextTransition"
              },
              "FastController": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${FastControllerFunction}",
                  "Payload.$": "$"
                },
                "TimeoutSeconds": 180,
                "Next": "WhatNext"
              },
              "SlowController": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${SlowControllerFunction}",
                  "Payload.$": "$"
                },
                "TimeoutSeconds": 900,
                "Next": "WhatNext"
              },
              "WhatNext": {
                "Type": "Choice",
                "Choices": [
                  {
                    "And": [
                      {
                        "Variable": "$.next",
                        "StringEquals": "",
                      },
                      {
                        "Variable": "$.result.status",
                        "StringEquals": "COMPLETE"
                      }
                    ],
                    "Next": "ExecutionDone"
                  },
                  {
                    "Variable": "$.next",
                    "StringEquals": "",
                    "Next": "ExecutionFailed"
                  },
                  {
                    "Variable": "$.delay",
                    "NumericGreaterThan": "0",
                    "Next": "WaitForNext"
                  }
                ],
                "Default": "NextTransition"
              },
              "ExecutionDone": {
                "Type": "Succeed"
              },
              "ExecutionFailed": {
                "Type": "Fail",
                "Cause": "Step not COMPLETE"
              },
              "WaitForNext": {
                "Type": "Wait",
                "SecondsPath": "$.delay",
                "Next": "NextTransition"
              },
              "NextTransition": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.speed",
                    "StringEquals": "slow",
                    "Next": "NextTransitionSlow"
                  }
                ],
                "Default": "NextTransitionFast"
              },
              "NextTransitionSlow": {
                "Type": "Pass",
                "Result": "$.next",
                "ResultPath": "$.this",
                "Next": "SlowController"
              },
              "NextTransitionFast": {
                "Type": "Pass",
                "Result": "$.next",
                "ResultPath": "$.this",
                "Next": "FastController"
              }
            }
          }
        - {
            FastControllerFunction: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}-lambda-bua-controller-fast",
            SlowControllerFunction: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}-lambda-bua-controller-slow"
          }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName
        - Key: resource-type
          Value: stepfunction
        - Key: resource-class
          Value: data
