AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS parameters
Parameters:
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  RDSParamsID:
    Description: RDS params ID
    Type: String
  RDSDomain:
    Description: RDS domain name
    Type: String
  RDSSecret:
    Description: RDS Secret Name
    Type: String
  RDSUpdateID:
    Description: RDS Update ID
    Type: String
  RDSSuffix:
    Description: RDS Suffix
    Type: String
    Default: "bua-sql"
  RDSSchema:
    Description: RDS Schema
    Type: String
    Default: "Turkey_BLU"
  RDSInstanceClass:
    Description: RDS Instance Class
    Type: String
    Default: "DBInstanceClassR6i"
  RDSInstanceType:
    Description: RDS Instance Type
    Type: String
    Default: "8xlarge"
  RDSMySQLVersion:
    Description: RDS MySQL Version
    Type: String
    Default: "8.0.32"
  SQLSecret:
    Description: SQL Secret Name
    Type: String
  RDSDNSAlias:
    Description: RDS DNS Alias
    Type: String
  HostedZoneId:
    Description: Route53 hosted zone id
    Type: String
  EKSClusterName:
    Description: EKS cluster name
    Type: String
  EKSNodeGroupName:
    Description: EKS node group name
    Type: String
  ADHBucketName:
    Description: Bucket to put files for ADH in
    Type: String
  NotifySteps:
    Description: Steps to execute on notification
    Type: String
  SourceAccountID:
    Description: The expected account id for notifications
    Type: String

Resources:

  RDSSnapshotARNParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/snapshot_arn"
      Description: "RDS Snapshot ARN"
      Type: "String"
      Value: "not-set"

  RunDateParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/run_date"
      Description: "The date that the run is for"
      Type: "String"
      Value: "not-set"

  TodayParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/today"
      Description: "The day that the run is pretending is today"
      Type: "String"
      Value: "not-set"

  RDSSuffixParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/suffix"
      Description: "RDS Suffix"
      Type: "String"
      Value: !Ref RDSSuffix

  RDSSchemaParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/schema"
      Description: "RDS Schema"
      Type: "String"
      Value: !Ref RDSSchema

  RDSInstanceClassParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/instance_class"
      Description: "RDS Instance Class"
      Type: "String"
      Value: !Ref RDSInstanceClass

  RDSInstanceTypeParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/instance_type"
      Description: "RDS Instance Type"
      Type: "String"
      Value: !Ref RDSInstanceType

  RDSMySQLVersionParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/mysql_version"
      Description: "RDS MySQL Version"
      Type: "String"
      Value: !Ref RDSMySQLVersion

  RDSParamsIDParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/params_id"
      Description: "RDS ParamsID"
      Type: "String"
      Value: !Ref RDSParamsID

  RDSUpdateIDParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/update_id"
      Description: "RDS UpdateID"
      Type: "String"
      Value: !Ref RDSUpdateID

  RDSDomainParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/domain"
      Description: "RDS domain name"
      Type: "String"
      Value: !Ref RDSDomain

  RDSSecretParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/rdssecret"
      Description: "RDS secret name"
      Type: "String"
      Value: !Ref RDSSecret

  SQLSecretParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/sqlsecret"
      Description: "SQL secret name"
      Type: "String"
      Value: !Ref SQLSecret

  RDSDNSAliasParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/rds_dns_alias"
      Description: "RDS DNS alias"
      Type: "String"
      Value: !Ref RDSDNSAlias

  HostedZoneIdParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/hosted_zone_id"
      Description: "Route53 zone ID"
      Type: "String"
      Value: !Ref HostedZoneId

  EKSClusterNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/cluster_name"
      Description: "EKS Cluster Name"
      Type: "String"
      Value: !Ref EKSClusterName

  EKSNodeGroupNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/node_group_name"
      Description: "EKS Node Group Name"
      Type: "String"
      Value: !Ref EKSNodeGroupName

  ADHBucketNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/adh_bucket_name"
      Description: "ADH Bucket Name"
      Type: "String"
      Value: !Ref ADHBucketName

  NotifyStepsParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/notify_steps"
      Description: "Steps to execute on notification"
      Type: "String"
      Value: !Ref NotifySteps

  SourceAccountIDParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/source_account_id"
      Description: "The expected source account for notificiations"
      Type: "String"
      Value: !Ref SourceAccountID
