AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS parameters
Parameters:
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  RDSDomain:
    Description: RDS domain name
    Type: String
  RDSSecret:
    Description: RDS Secret Name
    Type: String
  SQLSecret:
    Description: SQL Secret Name
    Type: String
  RDSDNSAlias:
    Description: RDS DNS Alias
    Type: String
  HostedZoneId:
    Description: Route53 hosted zone id
    Type: String
  EKSClusterName:
    Description: EKS cluster name
    Type: String
  EKSNodeGroupName:
    Description: EKS node group name
    Type: String
  ADHBucketName:
    Description: Bucket to put files for ADH in
    Type: String

Resources:

  RDSDomainParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/domain"
      Description: "RDS domain name"
      Type: "String"
      Value: !Ref RDSDomain

  RDSSecretParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/rdssecret"
      Description: "RDS secret name"
      Type: "String"
      Value: !Ref RDSSecret

  SQLSecretParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/sqlsecret"
      Description: "SQL secret name"
      Type: "String"
      Value: !Ref SQLSecret

  RDSDNSAliasParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/rds_dns_alias"
      Description: "RDS DNS alias"
      Type: "String"
      Value: !Ref RDSDNSAlias

  HostedZoneIdParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/hosted_zone_id"
      Description: "Route53 zone ID"
      Type: "String"
      Value: !Ref HostedZoneId

  EKSClusterNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/cluster_name"
      Description: "EKS Cluster Name"
      Type: "String"
      Value: !Ref EKSClusterName

  EKSNodeGroupNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/node_group_name"
      Description: "EKS Node Group Name"
      Type: "String"
      Value: !Ref EKSNodeGroupName

  ADHBucketNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/adh_bucket_name"
      Description: "ADH Bucket Name"
      Type: "String"
      Value: !Ref ADHBucketName
