AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS buckets
Parameters:
  EnvironmentName:
    Description: The name of the environment to deploy into
    Type: String
    AllowedValues: [ "dev", "tst", "prd" ]
  ClassName:
    Description: The class of the environment to deploy into
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  ResourcePrefixIAM:
    Description: Prefix to assign to resources
    Type: String
  OrganizationID:
    Type: String
    Default: "o-oswlt23l9n"

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join [ "" , [ !Ref ResourcePrefix , "-s3-bua" ] ]
      AccessControl: "Private"
      VersioningConfiguration:
        Status: 'Enabled'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !Join [ "" , [ "arn:aws:sqs:" , !Ref "AWS::Region" , ":" , !Ref "AWS::AccountId" , ":" , !Ref ResourcePrefix , "-sqs-bua-controller-fast-queue" ] ]
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "schedule/fast/"
          - Queue: !Join [ "" , [ "arn:aws:sqs:" , !Ref "AWS::Region" , ":" , !Ref "AWS::AccountId" , ":" , !Ref ResourcePrefix , "-sqs-bua-controller-slow-queue" ] ]
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "schedule/slow/"
          - Queue: !Join [ "" , [ "arn:aws:sqs:" , !Ref "AWS::Region" , ":" , !Ref "AWS::AccountId" , ":" , !Ref ResourcePrefix , "-sqs-bua-controller-next-queue" ] ]
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "schedule/next/"
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName
        - Key: resource-type
          Value: s3
        - Key: resource-class
          Value: data

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowDeployToManageStateMachines
            Action:
              - "s3:Get*"
              - "s3:List*"
              - "s3:Put*"
            Effect: Allow
            Resource:
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/states/*"
            Principal:
              AWS:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ResourcePrefixIAM}_CloudformationDeployRole"
          - Sid: AllowDeployToReadLambdaLayers
            Action:
              - "s3:Get*"
              - "s3:List*"
            Effect: Allow
            Resource:
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/lambda/*"
            Principal:
              AWS:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ResourcePrefixIAM}_CloudformationDeployRole"
          - Sid: AllowProvisionToPublishLambdaLayers
            Action:
              - "s3:Get*"
              - "s3:List*"
              - "s3:Put*"
            Effect: Allow
            Resource:
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/lambda/*"
            Principal:
              AWS:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ResourcePrefixIAM}_CloudformationProvisionRole"
          - Sid: AllowSSLRequestsOnly
            Action: "s3:*"
            Effect: Deny
            Resource:
            - !GetAtt Bucket.Arn
            - !Sub "${Bucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
            Principal: "*"
          - Sid: RestrictGetObjectToOrg
            Action: "s3:GetObject"
            Effect: Deny
            Resource:
              - !Sub "${Bucket.Arn}/*"
            Condition:
              StringNotEquals:
                aws:PrincipalOrgID:
                  - !Ref OrganizationID
            Principal: "*"
          - Sid: DenyPublicReadACL
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:PutObject"
              - "s3:PutObjectAcl"
            Resource:
            - !Sub "${Bucket.Arn}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - authenticated-read
          - Sid: DenyPublicReadGrant
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:PutObject"
              - "s3:PutObjectAcl"
            Resource:
            - !Sub "${Bucket.Arn}/*"
            Condition:
              StringLike:
                s3:x-amz-grant-read:
                  - "*http://acs.amazonaws.com/groups/global/AllUsers*"
                  - "*http://acs.amazonaws.com/groups/global/AuthenticatedUsers*"
          - Sid: DenyPublicListACL
            Effect: Deny
            Principal: "*"
            Action: "s3:PutBucketAcl"
            Resource:
            - !GetAtt Bucket.Arn
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - authenticated-read
          - Sid: DenyPublicListGrant
            Effect: Deny
            Principal: "*"
            Action: "s3:PutBucketAcl"
            Resource:
            - !GetAtt Bucket.Arn
            Condition:
              StringLike:
                s3:x-amz-grant-read:
                  - "*http://acs.amazonaws.com/groups/global/AllUsers*"
                  - "*http://acs.amazonaws.com/groups/global/AuthenticatedUsers*"
