AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS parameters
Parameters:
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  RDSDomain:
    Description: RDS domain name
    Type: String

Resources:

  RDSDomainParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/domain"
      Description: "RDS domain name"
      Type: "String"
      Value: !Ref RDSDomain
