AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS parameters
Parameters:
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String
  RDSDomain:
    Description: RDS domain name
    Type: String
  HostedZoneId:
    Description: Route53 hosted zone id
    Type: String
  EKSClusterName:
    Description: EKS cluster name
    Type: String

Resources:

  RDSDomainParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/domain"
      Description: "RDS domain name"
      Type: "String"
      Value: !Ref RDSDomain

  HostedZoneIdParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/hosted_zone_id"
      Description: "Route53 zone ID"
      Type: "String"
      Value: !Ref HostedZoneId

  EKSClusterNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${ResourcePrefix}/bua/cluster_name"
      Description: "EKS Cluster Name"
      Type: "String"
      Value: !Ref EKSClusterName
