AWSTemplateFormatVersion: "2010-09-09"
Description:  Configure AWS secrets
Parameters:
  EnvironmentName:
    Description: The name of the environment to deploy into
    Type: String
    AllowedValues: [ "dev", "tst", "prd" ]
  ClassName:
    Description: The class of the environment to deploy into
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String

Resources:

  RDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join [ "" , [ "cicd/" , !Ref ResourcePrefix , "/rds/bua" ] ]
      Description: 'BUA RDS Instance Master Credentials'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "core_admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName

  RDSPasswordsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join [ "" , [ "cicd/" , !Ref ResourcePrefix , "/rds/bua/passwords" ] ]
      Description: 'BUA RDS Instance User Passwords'
      SecretString: '{"sql":[]}'
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName
