AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy bottom up accruals controller state machine

Parameters:
  EnvironmentName:
    Description: The name of the environment to deploy into
    Type: String
    AllowedValues: [ "dev", "tst", "prd" ]
  ClassName:
    Description: The class of the environment to deploy into
    Type: String
  ResourcePrefix:
    Description: Prefix to assign to resources
    Type: String

Resources:

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub "states.${AWS::Region}.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: !Sub "${ResourcePrefix}-bua-controller"
      DefinitionS3Location:
        Bucket: !Sub "${ResourcePrefix}-bua"
        Key: "statemachines/controller_state_machine.json"
      DefinitionSubstitutions:
        ControllerFunction: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}-lambda-bua-controller"
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
        - Key: class
          Value: !Ref ClassName
        - Key: resource-type
          Value: stepfunction
        - Key: resource-class
          Value: data
